export {
  AudioClassificationPipeline,
  AutomaticSpeechRecognitionPipeline,
  DepthEstimationPipeline,
  DocumentQuestionAnsweringPipeline,
  FeatureExtractionPipeline,
  FillMaskPipeline,
  ImageCaptioningPipeline,
  ImageFeatureExtractionPipeline,
  ImageSegmentationPipeline,
  ImageToImagePipeline,
  ImageToTextPipeline,
  ObjectDetectionPipeline,
  QuestionAnsweringPipeline,
  SpeechRecognitionPipeline,
  SummarizationPipeline,
  TextClassificationPipeline,
  TextGenerationPipeline,
  TextToAudioPipeline,
  TextToTextGenerationPipeline,
  TokenClassificationPipeline,
  TranslationPipeline,
  ZeroShotAudioClassificationPipeline,
  ZeroShotClassifierPipeline,
  ZeroShotImageClassificationPipeline,
  ZeroShotObjectDetectionPipeline,
} from "./pipelines";
